// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _env(String key) {
    final value = dotenv.env[key];
    assert(value != null && value.isNotEmpty, 'Missing $key in .env');
    return value ?? '';
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_WEB'),
    appId: '1:794063817711:web:0cb9d50aa5b59237a4441a',
    messagingSenderId: '794063817711',
    projectId: 'shopping-app-8c5f9',
    authDomain: 'shopping-app-8c5f9.firebaseapp.com',
    databaseURL:
        'https://shopping-app-8c5f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-8c5f9.firebasestorage.app',
    measurementId: 'G-V8RL1WNR4N',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_ANDROID'),
    appId: '1:794063817711:android:dc115db9a0657e8ea4441a',
    messagingSenderId: '794063817711',
    projectId: 'shopping-app-8c5f9',
    databaseURL:
        'https://shopping-app-8c5f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-8c5f9.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_IOS'),
    appId: '1:794063817711:ios:736e8e5cba511303a4441a',
    messagingSenderId: '794063817711',
    projectId: 'shopping-app-8c5f9',
    databaseURL:
        'https://shopping-app-8c5f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-8c5f9.firebasestorage.app',
    iosClientId:
        '794063817711-cmub66hiufn672c0jfcc13jggdnjpvam.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_MACOS'),
    appId: '1:794063817711:ios:736e8e5cba511303a4441a',
    messagingSenderId: '794063817711',
    projectId: 'shopping-app-8c5f9',
    databaseURL:
        'https://shopping-app-8c5f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-8c5f9.firebasestorage.app',
    iosClientId:
        '794063817711-cmub66hiufn672c0jfcc13jggdnjpvam.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_WINDOWS'),
    appId: '1:794063817711:web:f59a347e3a41a6b0a4441a',
    messagingSenderId: '794063817711',
    projectId: 'shopping-app-8c5f9',
    authDomain: 'shopping-app-8c5f9.firebaseapp.com',
    databaseURL:
        'https://shopping-app-8c5f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-8c5f9.firebasestorage.app',
    measurementId: 'G-42PYDEZ580',
  );
}
